import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PrivacyPolicy: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="p-6 min-h-screen bg-gray-50 dark:bg-dark text-slate-900 dark:text-white pb-24">
      <div className="flex items-center mb-8 mt-4">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-gray-500 hover:text-slate-900 dark:text-gray-400 dark:hover:text-white transition-colors">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-bold ml-2">Privacy Policy</h1>
      </div>

      <div className="prose dark:prose-invert prose-sm max-w-none">
        <p className="text-gray-600 dark:text-gray-400 mb-6">Last updated: {new Date().toLocaleDateString()}</p>

        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>App name:</strong> Anam Ai<br />
          <strong>Support email:</strong> <a href="mailto:spacester7563@gmail.com" class="underline">spacester7563@gmail.com</a>
        </p>

        <p class="text-gray-600 dark:text-gray-400 mb-6">
          This Privacy Policy explains how Anam Ai (“we”, “our”, or “the App”) collects, uses, discloses, and stores information when you use the Anam Ai Android application. By installing or using the App you agree to this Privacy Policy.
        </p>

        <h3 class="text-xl font-semibold mb-2">Google Play Data Safety</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>Data types accessed/processed:</strong> User-supplied photos &amp; images (face images), inferred face/appearance attributes (scores for face features, hair, outfit, physique). These may be sensitive (biometric-derived attributes like face analysis).
        </p>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>Collection &amp; storage:</strong> The App does <strong>not</strong> transmit or store user data on any developer-controlled server for long-term storage. History and analysis results saved for convenience are stored <strong>locally on the user’s device only</strong> (local storage). Local data is removed if the user deletes/uninstalls the app or clears history from within the app.
        </p>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>Third parties:</strong> Image analysis and AI chat are processed using <strong>Google Gemini</strong> (a third-party AI service). When you use analysis features, relevant images/requests are transmitted to Google Gemini for processing and are subject to Google’s privacy policies.
        </p>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>Purpose:</strong> To provide appearance/face analysis, feature scores, and improvement advice.
        </p>

        <h3 class="text-xl font-semibold mb-2">1. What information we collect</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>a. Information you provide</strong><br />
          • Face images / photos that you choose to upload or capture within the App to receive analysis.<br />
          • Optional local notes/history you choose to save within the app’s local storage.
        </p>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>b. Information automatically derived</strong><br />
          • Analysis outputs — scores and attribute results generated by the AI (face score, features breakdown, hair, outfit, physique, suggestions). These outputs are derived from the images you submit.
        </p>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          <strong>c. No account or external database</strong><br />
          • The App does <strong>not</strong> require a login, and we do <strong>not</strong> maintain user accounts on our servers.<br />
          • We do <strong>not</strong> store user images or analysis results on any developer-controlled cloud or database.
        </p>

        <h3 class="text-xl font-semibold mb-2">2. How we use your information</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • To provide the core service: analyze the images you submit and return scores, feature breakdowns, and improvement advice.<br />
          • To store optional history <em>locally on your device</em> if you enable local history.<br />
          • To improve the App (only in aggregated/anonymous form if you explicitly opt in via an in-app option — otherwise no usage analytics are sent).
        </p>

        <h3 class="text-xl font-semibold mb-2">3. Third-party services &amp; Google Gemini</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • For the AI analysis, the App uses <strong>Google Gemini</strong>. When you request an analysis, image data and analysis requests are transmitted to Google’s APIs for processing.<br />
          • We do <strong>not</strong> control Google’s storage/retention practices. Please review Google’s privacy documentation for details about how Google collects, stores, and processes data when using its AI services.<br />
          • We do not combine Google-processed data with any other personal data for targeting or advertising.
        </p>

        <h3 class="text-xl font-semibold mb-2">4. Local storage &amp; deletion</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • Any history or saved analysis inside Anam Ai is stored <strong>only</strong> in the app’s local storage on your phone.<br />
          • If you uninstall the app, that local data will be removed from your device as part of the uninstall process. You can also remove history from within the app at any time using the clear/delete history function.<br />
          • If you want us to confirm deletion beyond what the app provides, contact us at <a href="mailto:spacester7563@gmail.com" class="underline">spacester7563@gmail.com</a> (we will respond describing what the app stores and the deletion options — note we cannot remove local files from your device remotely).
        </p>

        <h3 class="text-xl font-semibold mb-2">5. Children's privacy</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • The App is <strong>not intended</strong> for children under <strong>13 years</strong> of age. We do not knowingly collect images or information from children under 13. If you are a parent or guardian and become aware your child provided us with images, contact us to request guidance and steps we can suggest to remove local data (we cannot directly access your device to delete local files).
        </p>

        <h3 class="text-xl font-semibold mb-2">6. Security</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • We use reasonable technical measures to protect data processed by the App in transit (e.g., HTTPS/TLS when communicating with third-party APIs) and to protect local storage on the device according to typical mobile-app best practices.<br />
          • No system is 100% secure — we cannot guarantee absolute security of data in transit or on-device.
        </p>

        <h3 class="text-xl font-semibold mb-2">7. Sharing &amp; disclosures</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • <strong>We do not sell, rent, or trade</strong> personal data or images.<br />
          • We may share data with Google Gemini (for analysis) as described above.<br />
          • We may disclose information if required by law, to enforce our rights, or to protect the safety of users or the public.
        </p>

        <h3 class="text-xl font-semibold mb-2">8. Your rights &amp; choices</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          • <strong>Delete local history:</strong> Use the app’s internal controls to clear saved history.<br />
          • <strong>Uninstall:</strong> Uninstalling the app removes local data stored by the app on your device.<br />
          • <strong>Contact us:</strong> For privacy questions or requests, email <a href="mailto:spacester7563@gmail.com" class="underline">spacester7563@gmail.com</a>. We will respond in a reasonable time to help you understand what the app stores and available deletion options.
        </p>

        <h3 class="text-xl font-semibold mb-2">9. Contact</h3>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          If you have questions about this Privacy Policy, email: <a href="mailto:spacester7563@gmail.com" class="underline">spacester7563@gmail.com</a>.
        </p>
      
      </div>
    </div>
  );
};

export default PrivacyPolicy;
