import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TermsConditions: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="p-6 min-h-screen bg-gray-50 dark:bg-dark text-slate-900 dark:text-white pb-24">
      <div className="flex items-center mb-8 mt-4">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-gray-500 hover:text-slate-900 dark:text-gray-400 dark:hover:text-white transition-colors">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-bold ml-2">Terms & Conditions</h1>
      </div>

      <div className="prose dark:prose-invert prose-sm max-w-none">
        <p className="text-gray-600 dark:text-gray-400 mb-6">Last updated: {new Date().toLocaleDateString()}</p>

         <p class="text-gray-600 dark:text-gray-400 mb-6">
        By downloading or using Anam Ai, you agree to the following Terms and Conditions.
      </p>

      <h3 class="text-xl font-semibold mb-2">1. Service Description</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        Anam Ai provides AI-based appearance analysis and improvement advice based on user-
        submitted images. All results are automatically generated by artificial intelligence.
      </p>

      <h3 class="text-xl font-semibold mb-2">2. User Responsibility</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        Users are responsible for any images they upload and must ensure they have the right
        to use them. Uploading illegal or unauthorized content is prohibited.
      </p>

      <h3 class="text-xl font-semibold mb-2">3. No Professional Advice</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        Results and recommendations provided by Anam Ai are for informational and
        entertainment purposes only and should not be considered medical, cosmetic, or
        professional advice.
      </p>

      <h3 class="text-xl font-semibold mb-2">4. Third-Party Services</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        The app relies on third-party AI services such as Google Gemini. We are not responsible
        for any issues arising from the use of these third-party services.
      </p>

      <h3 class="text-xl font-semibold mb-2">5. Limitation of Liability</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        Anam Ai and its developers are not liable for any damages resulting from the use
        or inability to use the app or reliance on AI-generated content.
      </p>

      <h3 class="text-xl font-semibold mb-2">6. Termination</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        We reserve the right to suspend or terminate access to the app if these terms are violated.
        Users may stop using the app at any time by uninstalling it.
      </p>

      <h3 class="text-xl font-semibold mb-2">7. Governing Law</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        These Terms shall be governed by and interpreted in accordance with the laws of India.
      </p>

      <h3 class="text-xl font-semibold mb-2">8. Contact</h3>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        For any questions regarding these Terms, please contact:
        <span class="font-medium">spacester7563@gmail.com</span>
      </p>
      </div>
    </div>
  );
};

export default TermsConditions;
